listen_address = "0.0.0.0"
concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "<your test runner name>"
  url = "https://gitlab.com/"
  token = "<your token>"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    Insecure = false
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:19.03.13-dind"
    privileged = true
    disable_cache = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]
    shm_size = 0
    [[runners.docker.services]]
      name = "docker:19.03.13-dind"
      alias = "docker"


